name: Github Docker CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4']
        os_type: ['debian', 'alpine']
        php_type: ['fpm', 'cli']
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action@v1.0.1
      - name: Build the Docker image
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_IMAGE: ${{ matrix.php_version }}-${{ matrix.php_type }}
          DOCKER_TEMPLATE: ${{ matrix.php_version }}-${{ matrix.php_type }}-${{ matrix.os_type }}
          IMAGE_TAG_BASE: noitran/php-base:${{ matrix.php_version }}-${{ matrix.php_type }}-${{ matrix.os_type }}
        run: |
          echo "::set-env name=php_version::${PHP_VERSION}"
          echo "::set-env name=docker_image::${DOCKER_IMAGE}"
          echo "::set-env name=docker_template::${DOCKER_TEMPLATE}"
          echo "::set-env name=image_tag_latest::${IMAGE_TAG_BASE}-latest"
          echo "::set-env name=image_tag_versioned::${IMAGE_TAG_BASE}-${{ github.event.release.tag_name }}"

          sed -e "s/%%DOCKER_IMAGE%%/${DOCKER_IMAGE}/g" ${DOCKER_TEMPLATE}/Dockerfile.template > ${DOCKER_TEMPLATE}/Dockerfile
          docker build -f ${DOCKER_TEMPLATE}/Dockerfile . -t ${{ image_tag_latest }}
          docker image ls
      - name: Test image which was built
        if: success()
        run: |
          GOSS_FILES_PATH=${{ env.docker_template }} dgoss run -t ${{ image_tag_latest }}
      - name: Push image to Docker hub
        if: success()
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ${{ image_tag_latest }}
          docker tag ${{ image_tag_latest }} ${{ image_tag_versioned }}
          docker push ${{ image_tag_versioned }}
          docker logout
