name: Github Docker CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [74]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          PHP_VERSION: ${{ matrix.php_version }}
        run: |
          export TAG_VERSION=${PHP_VERSION:0:1}.${PHP_VERSION:1:1}
          docker build . --file Dockerfile-${{ matrix.php_version }} --tag noitran/php-fpm-base:latest-${TAG_VERSION}
          docker image ls
      - name: Test image which was built
        if: success()
        env:
          PHP_VERSION: ${{ matrix.php_version }}
        run: |
          echo "This is test"
      - name: Push image to Docker hub
        if: success()
        env:
          PHP_VERSION: ${{ matrix.php_version }}
        run: |
          export TAG_VERSION=${PHP_VERSION:0:1}.${PHP_VERSION:1:1}
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push noitran/php-fpm-base:latest-${TAG_VERSION}
          docker logout
