name: Github Docker CI

# https://github.community/t/support-saving-environment-variables-between-steps/16230/6

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_IMAGE: ${{ matrix.php_version }}-fpm
          TEMPLATE: ${{ matrix.php_version }}-fpm-debian
          IMAGE_TAG: noitran/php-base:${{ matrix.php_version }}-fpm-debian-latest
        run: |
          sed -e "s/%%DOCKER_IMAGE%%/${DOCKER_IMAGE}/g" ${TEMPLATE}/Dockerfile.template > ${TEMPLATE}/Dockerfile
          docker build -t ${IMAGE_TAG} ${TEMPLATE}
          docker image ls
      - name: Test image which was built
        if: success()
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_IMAGE: ${{ matrix.php_version }}-fpm
          TEMPLATE: ${{ matrix.php_version }}-fpm-debian
          IMAGE_TAG: noitran/php-base:${{ matrix.php_version }}-fpm-debian-latest
        run: |
          echo "This is test"
      - name: Push image to Docker hub
        if: success()
        env:
          PHP_VERSION: ${{ matrix.php_version }}
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker images
          docker push ${IMAGE_TAG}
          docker logout
